channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- bokeh
- cython
- cudatoolkit=10.0
- dill
- future
- h5py
- ipython
- ipyparallel
- ipykernel
- joblib
- jupyter
- jupyterlab
- matplotlib
- nose
- nb_conda
- nb_conda_kernels
- nodejs
- numpy
- opencv
- pandas
- peakutils
- pims
- pytest
- pytorch
- scipy
- scikit-image
- scikit-learn
- scikit-video
- seaborn
- spyder
- tifffile
- torchvision
- tqdm

