#!/usr/bin/env python
import fire

class CLI(object):
    """Facilitate writing a Neurodata without borders (NWB) file."""

    def __init__(self, filepath):
        self.io = open(filepath, 'a')
        self.filepath = filepath

    def noop(self):
        "add nothing to nwbfile"
        return self

    def __str__(self):
        """Write data & close io."""
        if not self.io is None:
            self.io.close()
        return f"Wrote to {self.filepath}"

if __name__ == '__main__':
    fire.Fire(CLI)