#!/usr/bin/env python

import av, click, moviepy.editor as mpy

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS)
@click.argument("mp4_file", type=click.Path(exists=True))
@click.option("--av", "lib", flag_value="av", default=True)
@click.option("--moviepy", "lib", flag_value="moviepy")
def main(mp4_file: str, lib: str):
    """Count frames of .mp4"""
    if mp4_file is None:
        # print help and exit
        ctx = click.get_current_context()
        click.echo(ctx.get_help())
        exit(0)
    
    frame_count = 0

    if lib=="av":
        container = av.open(mp4_file)
        for _ in container.decode(video=0):
            frame_count += 1
    elif lib=="moviepy":    
        myclip = mpy.VideoFileClip(mp4_file)
        for _ in myclip.iter_frames():
            frame_count += 1
        
    print(f"number of frames: {frame_count}")

if __name__ == '__main__':
    main()